### ISSUE TITLE
xCrawl.crawlFile 函数不能完美的兼容linux

### ISSUE THREAD

**Issue by h7ml** [coder-hxl/x-crawl#26]
### Bug 预期

https://github.com/dext7r/puppeteer/blob/master/src/utils/bilibili.ts#L45

![image](https://user-images.githubusercontent.com/55233292/234168903-befd3d15-173c-4781-a03d-e39f38d2fbfe.png)

在window下是可以直接新建這個目錄并写入的。
但是在linux报错如下
```log
Run pnpm task

> @dext7r/puppeteer@0.0.1 task /home/runner/work/puppeteer/puppeteer
> npx ts-node ./src/serve

Start crawling - name: page, mode: async, total: 1 
Id: 1 - Crawl does not need to sleep, send immediately
Crawl the final result:
  Success - total: 1, ids: [ 1 ]
    Error - total: 0, ids: [  ]
Start crawling - name: file, mode: async, total: 9 
Id: 1 - Crawl does not need to sleep, send immediately
Id: 2 - Crawl does not need to sleep, send immediately
Id: 3 - Crawl does not need to sleep, send immediately
Id: 4 - Crawl does not need to sleep, send immediately
Id: 5 - Crawl does not need to sleep, send immediately
Id: [6](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:7) - Crawl does not need to sleep, send immediately
Id: [7](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:8) - Crawl does not need to sleep, send immediately
Id: [8](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:9) - Crawl does not need to sleep, send immediately
Id: [9](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:10) - Crawl does not need to sleep, send immediately
Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (node:fs:1396:3)
    at /home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:46:[10](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:11)
    at Array.reduce (<anonymous>)
    at mkdirDirSync (/home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:43:[12](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:13))
    at fileSingleResultHandle (/home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:951:7)
    at /home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:[13](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:14)5:[21](https://github.com/dext7r/puppeteer/actions/runs/4793322343/jobs/8525664251#step:6:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT'
}
Error: The operation was canceled.
```

### 最小可重复的例子

```TypeScript
import xCrawl from 'x-crawl';
import path from 'path';
import fs from 'fs/promises';

const bilibiliXCrawl = xCrawl({ mode: 'async' });
export function getCurrentDate(separator: string = '-') {


  // 调用 crawlFile API 爬取图片
  await bilibiliXCrawl.crawlFile({
    targets: [...urls],
    // storeDir: `./bilibili/${getCurrentDate('/')}`,
    storeDir,
  });
  // 关闭页面
  page.close();

  // 关闭浏览器
  browser.close();
}
```

### 报错信息

Error: ENOENT: no such file or directory, mkdir

### x-crawl 版本

 "x-crawl": "^6.0.1"

### Node 版本

18

### 包管理器

pnpm

### 包管理器版本

7.13.2

**Comment by coder-hxl** [comment]
你好，我感觉这是权限问题。crawlFile API 内部是使用 fs.mkdirSync 创建文件夹的

**Comment by coder-hxl** [comment]
你可以试试 fs.mkdirSync 创建一个文件夹看看是否可以

**Comment by coder-hxl** [comment]
你好，有没有看见 crawlFile 创建的文件夹

**Comment by h7ml** [comment]
> 你好，有没有看见 crawlFile 创建的文件夹

linux 跑 https://github.com/coder-hxl/x-crawl#detailed-target-array-config---crawlfiledetailtargetconfig 直接报错，`storeDir` 为 `upload/2023/04/25`  文件夹`upload/2023/04/25` 不存在，但是文件夹如果只有一级可以直接保存文件并新建这个文件夹。

**Comment by h7ml** [comment]
最小化复现案例如下 https://github.com/dext7r/puppeteer/blob/x-crawl-crawlFile/src/utils/bilibili.ts

日志如下[action log](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181)

```log
Run pnpm task
  
> @dext7r/puppeteer@0.0.1 task /home/runner/work/puppeteer/puppeteer
> npx ts-node ./src/serve
Start crawling - name: page, mode: async, total: 1 
Id: 1 - Crawl does not need to sleep, send immediately
Crawl the final result:
  Success - total: 1, ids: [ 1 ]
    Error - total: 0, ids: [  ]
Start crawling - name: file, mode: async, total: 9 
Id: 1 - Crawl does not need to sleep, send immediately
Id: 2 - Crawl does not need to sleep, send immediately
Id: 3 - Crawl does not need to sleep, send immediately
Id: 4 - Crawl does not need to sleep, send immediately
Id: 5 - Crawl does not need to sleep, send immediately
Id: [6](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:6) - Crawl does not need to sleep, send immediately
Id: [7](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:8) - Crawl does not need to sleep, send immediately
Id: [8](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:9) - Crawl does not need to sleep, send immediately
Id: 9 - Crawl does not need to sleep, send immediately
Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (node:fs:1396:3)
    at /home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:46:[10](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:11)
    at Array.reduce (<anonymous>)
    at mkdirDirSync (/home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:43:[12](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:13))
    at fileSingleResultHandle (/home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:951:7)
    at /home/runner/work/puppeteer/puppeteer/node_modules/.pnpm/x-crawl@6.0.1_typescript@4.9.5/node_modules/x-crawl/dist/index.js:[13](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:14)5:[21](https://github.com/dext7r/puppeteer/actions/runs/4794171737/jobs/8527284181#step:6:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 4) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT'
}
```

**Comment by coder-hxl** [comment]
@h7ml 感谢您的 Bug 反馈，该 Bug 将在 v7 版本中修复

**Comment by coder-hxl** [comment]
v7 版本已经发布，可以试试看
